spring:
  application:
    name: "Muse"
    version: @project.version@
    description: "Molecular Upload Submission sErvice"

server:
  port: 8090

songScoreClient:
  songRootUrl: "http://localhost:8080/"
  scoreRootUrl: "http://localhost:8087/"
  systemApiToken: f69b726d-d40f-4261-b105-1ec7e6bf04d5

---
spring.profiles: secure
auth:
  jwtPublicKeyUrl: "http://localhost:8081/oauth/token/public_key"
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nSET ME IF YOU DONT HAVE A URL, BUT URL TAKES PRIORITY\n-----END PUBLIC KEY-----"
  scopes:
    read:
      - CANCOGEN-DATA.READ
    write:
      - CANCOGEN-DATA.WRITE
