spring:
  application:
    name: "Muse"
    version: @project.version@
    description: "Molecular Upload Submission sErvice"

server:
  port: 8080

cors:
  domainPatterns:
    - "http://localhost:3000"
    - "https://localhost:3000"
  maxAge: 3600

codecConfig:
  maxHeadersSize: 16384

submitUpload:
  maxInFlight: 5

postgres:
  host: localhost
  port: 5432
  database: muse
  username: postgres
  password: password
  maxPoolIdleTimeMs: 1000
  maxPoolSize: 20

ariaclient:
  songRootUrl: "http://localhost:8089/"
  scoreRootUrl: "http://localhost:8087/"
  clientId: adminId
  clientSecret: adminSecret
  tokenUrl: http://localhost:8081/oauth/token
  retryMaxAttempts: 3
  retryDelaySec: 10

auth:
  jwtPublicKeyUrl: "http://localhost:8081/oauth/token/public_key"
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nSET ME IF YOU DONT HAVE A URL, BUT URL TAKES PRIORITY\n-----END PUBLIC KEY-----"
  scopes:
    study:
      prefix: "muse."
      suffix: ".WRITE"
    system: DOMAIN.WRITE

management:
  endpoint:
    health:
      show-details: NEVER
